export interface MovieModel {
    adult: boolean,
    backdrop_path: string,
    belongs_to_collection: object,
    budget: number,
    genres: [],
    homepage: string,
    id: number,
    imdb_id: string,
    original_language: string,
    original_title: string,
    overview: string,
    popularity: number,
    poster_path: string,
    production_companies: [],
    production_countries: [],
    release_date: string,
    revenue: number,
    runtime: number,
    spoken_languages: [],
    status: string,
    tagline: string,
    title: string,
    video: boolean,
    vote_average: number,
    vote_count: number
}
export interface MoviesModel{
    popularity: number,
    vote_count: number,
    video: boolean,
    poster_path: string,
    id: number,
    adult: string,
    backdrop_path: string,
    original_language: string,
    original_title: string,
    genre_ids: [],
    title: string,
    vote_average:number,
    overview: string,
    release_date: string
}

